apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-env-demo
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command: ["/bin/bash", "-c", "while true; do echo \"App: $APP_NAME | Env: $ENVIRONMENT | Debug: $DEBUG_MODE\"; sleep 5; done"]
      env:
        - name: APP_NAME
          value: "MyDemoApp"
        - name: ENVIRONMENT
          value: "dev"
        - name: DEBUG_MODE
          value: "true"
